bcm-2xxx-rpi: add upstream status in u-boot patch
Issue: LINCD-12938

There is below building error if missing upstream status in patch,
ERROR: u-boot-1_2023.04-r0 do_patch: QA Issue: Missing Upstream-Status in patch
So, add it.

Signed-off-by: Meng Li <Meng.Li@windriver.com>