bcm-2xxx-rpi: adjust patch to compatible with latest u-boot
Issue: LINCD-13789

- There is below build error in apply the patch file due to u-boot rpi env
  file change.
  ERROR: Applying patch 0002-rpi.h-Add-ostree-default-variables.patch
  Adjust this patch to compatible with latest u-boot.

- Patch file 0001-bcm2835-Add-simiple-framebuffer-for-use-with-fkms.patch
  removed from bcm-2xxx-rpi layer.
  Above patch already part of latest u-boot source commit 28cd244e847c, so
  this patch is removed to resolve patching error.

Signed-off-by: Rajeshkumar Ramasamy <rajeshkumar.ramasamy@windriver.com>